name: debug

# https://help.github.com/cn/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on:
  release:
    types: [published]

  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          mkdir -p artifact/dist
          mkdir -p lean/packages
          ln -sf `pwd`/lean/packages artifact/dist/diy-packages
          ls -l
          ls -l artifact/dist/diy-packages
          ls -l > artifact/dist/list.txt
          echo pwd: $(pwd)


      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact
          path: artifact/dist

